// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/account.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Account struct {
	Id                   []byte   `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Type                 *uint32  `protobuf:"varint,2,req,name=type" json:"type,omitempty"`
	Utxos                []*UTXO  `protobuf:"bytes,3,rep,name=utxos" json:"utxos,omitempty"`
	StorageRoot          []byte   `protobuf:"bytes,6,opt,name=storageRoot" json:"storageRoot,omitempty"`
	CodeHash             []byte   `protobuf:"bytes,7,opt,name=codeHash" json:"codeHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3a8b28a2e7a7402, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Account) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Account) GetUtxos() []*UTXO {
	if m != nil {
		return m.Utxos
	}
	return nil
}

func (m *Account) GetStorageRoot() []byte {
	if m != nil {
		return m.StorageRoot
	}
	return nil
}

func (m *Account) GetCodeHash() []byte {
	if m != nil {
		return m.CodeHash
	}
	return nil
}

type UTXO struct {
	Id                   *Ticket  `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	LocatedHeight        *uint32  `protobuf:"varint,2,req,name=locatedHeight" json:"locatedHeight,omitempty"`
	EffectHeight         *uint32  `protobuf:"varint,3,req,name=effectHeight" json:"effectHeight,omitempty"`
	Value                []byte   `protobuf:"bytes,4,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UTXO) Reset()         { *m = UTXO{} }
func (m *UTXO) String() string { return proto.CompactTextString(m) }
func (*UTXO) ProtoMessage()    {}
func (*UTXO) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3a8b28a2e7a7402, []int{1}
}

func (m *UTXO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UTXO.Unmarshal(m, b)
}
func (m *UTXO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UTXO.Marshal(b, m, deterministic)
}
func (m *UTXO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UTXO.Merge(m, src)
}
func (m *UTXO) XXX_Size() int {
	return xxx_messageInfo_UTXO.Size(m)
}
func (m *UTXO) XXX_DiscardUnknown() {
	xxx_messageInfo_UTXO.DiscardUnknown(m)
}

var xxx_messageInfo_UTXO proto.InternalMessageInfo

func (m *UTXO) GetId() *Ticket {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *UTXO) GetLocatedHeight() uint32 {
	if m != nil && m.LocatedHeight != nil {
		return *m.LocatedHeight
	}
	return 0
}

func (m *UTXO) GetEffectHeight() uint32 {
	if m != nil && m.EffectHeight != nil {
		return *m.EffectHeight
	}
	return 0
}

func (m *UTXO) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type ClearTime struct {
	LastClearTime        *int64   `protobuf:"varint,1,req,name=lastClearTime" json:"lastClearTime,omitempty"`
	LastEffectHeight     *uint32  `protobuf:"varint,2,req,name=lastEffectHeight" json:"lastEffectHeight,omitempty"`
	NextClearTime        *int64   `protobuf:"varint,3,req,name=nextClearTime" json:"nextClearTime,omitempty"`
	NextEffectHeight     *uint32  `protobuf:"varint,4,req,name=nextEffectHeight" json:"nextEffectHeight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearTime) Reset()         { *m = ClearTime{} }
func (m *ClearTime) String() string { return proto.CompactTextString(m) }
func (*ClearTime) ProtoMessage()    {}
func (*ClearTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3a8b28a2e7a7402, []int{2}
}

func (m *ClearTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearTime.Unmarshal(m, b)
}
func (m *ClearTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearTime.Marshal(b, m, deterministic)
}
func (m *ClearTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearTime.Merge(m, src)
}
func (m *ClearTime) XXX_Size() int {
	return xxx_messageInfo_ClearTime.Size(m)
}
func (m *ClearTime) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearTime.DiscardUnknown(m)
}

var xxx_messageInfo_ClearTime proto.InternalMessageInfo

func (m *ClearTime) GetLastClearTime() int64 {
	if m != nil && m.LastClearTime != nil {
		return *m.LastClearTime
	}
	return 0
}

func (m *ClearTime) GetLastEffectHeight() uint32 {
	if m != nil && m.LastEffectHeight != nil {
		return *m.LastEffectHeight
	}
	return 0
}

func (m *ClearTime) GetNextClearTime() int64 {
	if m != nil && m.NextClearTime != nil {
		return *m.NextClearTime
	}
	return 0
}

func (m *ClearTime) GetNextEffectHeight() uint32 {
	if m != nil && m.NextEffectHeight != nil {
		return *m.NextEffectHeight
	}
	return 0
}

func init() {
	proto.RegisterType((*Account)(nil), "protobuf.Account")
	proto.RegisterType((*UTXO)(nil), "protobuf.UTXO")
	proto.RegisterType((*ClearTime)(nil), "protobuf.ClearTime")
}

func init() { proto.RegisterFile("protobuf/account.proto", fileDescriptor_f3a8b28a2e7a7402) }

var fileDescriptor_f3a8b28a2e7a7402 = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0xc7, 0xc9, 0x47, 0x6d, 0x9d, 0x7e, 0x50, 0x16, 0x91, 0xa5, 0xa7, 0x25, 0xf4, 0x10, 0x3c,
	0x54, 0xe8, 0x1b, 0x88, 0x08, 0xbd, 0x09, 0x4b, 0x05, 0xaf, 0xeb, 0x66, 0xda, 0x2e, 0xd6, 0x6c,
	0x49, 0x26, 0x52, 0xdf, 0xc0, 0xab, 0x4f, 0xe2, 0x2b, 0x4a, 0x76, 0xdb, 0x98, 0xe8, 0x2d, 0xf3,
	0x9b, 0x7f, 0x7e, 0xf3, 0x5f, 0xb8, 0x3e, 0x14, 0x96, 0xec, 0x4b, 0xb5, 0xb9, 0x55, 0x5a, 0xdb,
	0x2a, 0xa7, 0x85, 0x03, 0x6c, 0x70, 0xe6, 0xb3, 0x59, 0x93, 0xa0, 0x42, 0xe5, 0xa5, 0xd2, 0x64,
	0x6c, 0xee, 0x53, 0xc9, 0x57, 0x00, 0xfd, 0x3b, 0xff, 0x1f, 0x9b, 0x40, 0x68, 0x32, 0x1e, 0x88,
	0x30, 0x1d, 0xc9, 0xd0, 0x64, 0x8c, 0x41, 0x4c, 0x1f, 0x07, 0xe4, 0xa1, 0x08, 0xd3, 0xb1, 0x74,
	0xdf, 0x6c, 0x0e, 0xbd, 0x8a, 0x8e, 0xb6, 0xe4, 0x91, 0x88, 0xd2, 0xe1, 0x72, 0xb2, 0x38, 0xbb,
	0x17, 0x4f, 0xeb, 0xe7, 0x47, 0xe9, 0x97, 0x4c, 0xc0, 0xb0, 0x24, 0x5b, 0xa8, 0x2d, 0x4a, 0x6b,
	0x89, 0x5f, 0x88, 0x20, 0x1d, 0xc9, 0x36, 0x62, 0x33, 0x18, 0x68, 0x9b, 0xe1, 0x4a, 0x95, 0x3b,
	0xde, 0x77, 0xeb, 0x66, 0x4e, 0x3e, 0x03, 0x88, 0x6b, 0x1b, 0x13, 0x4d, 0xa1, 0xe1, 0x72, 0xfa,
	0x7b, 0x69, 0x6d, 0xf4, 0x2b, 0x92, 0xab, 0x38, 0x87, 0xf1, 0xde, 0x6a, 0x45, 0x98, 0xad, 0xd0,
	0x6c, 0x77, 0x74, 0xea, 0xda, 0x85, 0x2c, 0x81, 0x11, 0x6e, 0x36, 0xa8, 0xe9, 0x14, 0x8a, 0x5c,
	0xa8, 0xc3, 0xd8, 0x15, 0xf4, 0xde, 0xd5, 0xbe, 0x42, 0x1e, 0xbb, 0xf7, 0xfb, 0x21, 0xf9, 0x0e,
	0xe0, 0xf2, 0x7e, 0x8f, 0xaa, 0x58, 0x9b, 0x37, 0x74, 0xd7, 0x54, 0x49, 0x0d, 0x70, 0xd5, 0x22,
	0xd9, 0x85, 0xec, 0x06, 0xa6, 0x35, 0x78, 0x68, 0x5f, 0xf4, 0xb5, 0xfe, 0xf1, 0xda, 0x98, 0xe3,
	0xb1, 0x65, 0x8c, 0xbc, 0xb1, 0x03, 0x6b, 0x63, 0x0d, 0x3a, 0xc6, 0xd8, 0x1b, 0xff, 0xf2, 0x9f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xd2, 0x8d, 0xf9, 0x12, 0x0f, 0x02, 0x00, 0x00,
}
