// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/transaction.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AppTransactions struct {
	Txs                  []*AppTransaction `protobuf:"bytes,1,rep,name=txs" json:"txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AppTransactions) Reset()         { *m = AppTransactions{} }
func (m *AppTransactions) String() string { return proto.CompactTextString(m) }
func (*AppTransactions) ProtoMessage()    {}
func (*AppTransactions) Descriptor() ([]byte, []int) {
	return fileDescriptor_55be6871dfc7d2db, []int{0}
}

func (m *AppTransactions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppTransactions.Unmarshal(m, b)
}
func (m *AppTransactions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppTransactions.Marshal(b, m, deterministic)
}
func (m *AppTransactions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppTransactions.Merge(m, src)
}
func (m *AppTransactions) XXX_Size() int {
	return xxx_messageInfo_AppTransactions.Size(m)
}
func (m *AppTransactions) XXX_DiscardUnknown() {
	xxx_messageInfo_AppTransactions.DiscardUnknown(m)
}

var xxx_messageInfo_AppTransactions proto.InternalMessageInfo

func (m *AppTransactions) GetTxs() []*AppTransaction {
	if m != nil {
		return m.Txs
	}
	return nil
}

type AppTransaction struct {
	Version              *uint32          `protobuf:"varint,1,req,name=version" json:"version,omitempty"`
	Type                 *uint32          `protobuf:"varint,2,req,name=type" json:"type,omitempty"`
	From                 *TransactionFrom `protobuf:"bytes,3,req,name=from" json:"from,omitempty"`
	To                   *TransactionTo   `protobuf:"bytes,4,req,name=to" json:"to,omitempty"`
	Sign                 [][]byte         `protobuf:"bytes,5,rep,name=sign" json:"sign,omitempty"`
	Data                 []byte           `protobuf:"bytes,6,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AppTransaction) Reset()         { *m = AppTransaction{} }
func (m *AppTransaction) String() string { return proto.CompactTextString(m) }
func (*AppTransaction) ProtoMessage()    {}
func (*AppTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_55be6871dfc7d2db, []int{1}
}

func (m *AppTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppTransaction.Unmarshal(m, b)
}
func (m *AppTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppTransaction.Marshal(b, m, deterministic)
}
func (m *AppTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppTransaction.Merge(m, src)
}
func (m *AppTransaction) XXX_Size() int {
	return xxx_messageInfo_AppTransaction.Size(m)
}
func (m *AppTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_AppTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_AppTransaction proto.InternalMessageInfo

func (m *AppTransaction) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *AppTransaction) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *AppTransaction) GetFrom() *TransactionFrom {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *AppTransaction) GetTo() *TransactionTo {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *AppTransaction) GetSign() [][]byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

func (m *AppTransaction) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type FromCoin struct {
	Id                   []byte    `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Ticket               []*Ticket `protobuf:"bytes,2,rep,name=ticket" json:"ticket,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FromCoin) Reset()         { *m = FromCoin{} }
func (m *FromCoin) String() string { return proto.CompactTextString(m) }
func (*FromCoin) ProtoMessage()    {}
func (*FromCoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_55be6871dfc7d2db, []int{2}
}

func (m *FromCoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FromCoin.Unmarshal(m, b)
}
func (m *FromCoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FromCoin.Marshal(b, m, deterministic)
}
func (m *FromCoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FromCoin.Merge(m, src)
}
func (m *FromCoin) XXX_Size() int {
	return xxx_messageInfo_FromCoin.Size(m)
}
func (m *FromCoin) XXX_DiscardUnknown() {
	xxx_messageInfo_FromCoin.DiscardUnknown(m)
}

var xxx_messageInfo_FromCoin proto.InternalMessageInfo

func (m *FromCoin) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *FromCoin) GetTicket() []*Ticket {
	if m != nil {
		return m.Ticket
	}
	return nil
}

type TransactionFrom struct {
	Coins                []*FromCoin `protobuf:"bytes,1,rep,name=coins" json:"coins,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TransactionFrom) Reset()         { *m = TransactionFrom{} }
func (m *TransactionFrom) String() string { return proto.CompactTextString(m) }
func (*TransactionFrom) ProtoMessage()    {}
func (*TransactionFrom) Descriptor() ([]byte, []int) {
	return fileDescriptor_55be6871dfc7d2db, []int{3}
}

func (m *TransactionFrom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionFrom.Unmarshal(m, b)
}
func (m *TransactionFrom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionFrom.Marshal(b, m, deterministic)
}
func (m *TransactionFrom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionFrom.Merge(m, src)
}
func (m *TransactionFrom) XXX_Size() int {
	return xxx_messageInfo_TransactionFrom.Size(m)
}
func (m *TransactionFrom) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionFrom.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionFrom proto.InternalMessageInfo

func (m *TransactionFrom) GetCoins() []*FromCoin {
	if m != nil {
		return m.Coins
	}
	return nil
}

type ToCoin struct {
	Id                   []byte   `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Value                []byte   `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToCoin) Reset()         { *m = ToCoin{} }
func (m *ToCoin) String() string { return proto.CompactTextString(m) }
func (*ToCoin) ProtoMessage()    {}
func (*ToCoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_55be6871dfc7d2db, []int{4}
}

func (m *ToCoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToCoin.Unmarshal(m, b)
}
func (m *ToCoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToCoin.Marshal(b, m, deterministic)
}
func (m *ToCoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToCoin.Merge(m, src)
}
func (m *ToCoin) XXX_Size() int {
	return xxx_messageInfo_ToCoin.Size(m)
}
func (m *ToCoin) XXX_DiscardUnknown() {
	xxx_messageInfo_ToCoin.DiscardUnknown(m)
}

var xxx_messageInfo_ToCoin proto.InternalMessageInfo

func (m *ToCoin) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ToCoin) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type TransactionTo struct {
	Coins                []*ToCoin `protobuf:"bytes,1,rep,name=coins" json:"coins,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TransactionTo) Reset()         { *m = TransactionTo{} }
func (m *TransactionTo) String() string { return proto.CompactTextString(m) }
func (*TransactionTo) ProtoMessage()    {}
func (*TransactionTo) Descriptor() ([]byte, []int) {
	return fileDescriptor_55be6871dfc7d2db, []int{5}
}

func (m *TransactionTo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionTo.Unmarshal(m, b)
}
func (m *TransactionTo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionTo.Marshal(b, m, deterministic)
}
func (m *TransactionTo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionTo.Merge(m, src)
}
func (m *TransactionTo) XXX_Size() int {
	return xxx_messageInfo_TransactionTo.Size(m)
}
func (m *TransactionTo) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionTo.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionTo proto.InternalMessageInfo

func (m *TransactionTo) GetCoins() []*ToCoin {
	if m != nil {
		return m.Coins
	}
	return nil
}

type Ticket struct {
	Txid                 []byte   `protobuf:"bytes,1,req,name=txid" json:"txid,omitempty"`
	Index                *uint32  `protobuf:"varint,2,req,name=index" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ticket) Reset()         { *m = Ticket{} }
func (m *Ticket) String() string { return proto.CompactTextString(m) }
func (*Ticket) ProtoMessage()    {}
func (*Ticket) Descriptor() ([]byte, []int) {
	return fileDescriptor_55be6871dfc7d2db, []int{6}
}

func (m *Ticket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ticket.Unmarshal(m, b)
}
func (m *Ticket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ticket.Marshal(b, m, deterministic)
}
func (m *Ticket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ticket.Merge(m, src)
}
func (m *Ticket) XXX_Size() int {
	return xxx_messageInfo_Ticket.Size(m)
}
func (m *Ticket) XXX_DiscardUnknown() {
	xxx_messageInfo_Ticket.DiscardUnknown(m)
}

var xxx_messageInfo_Ticket proto.InternalMessageInfo

func (m *Ticket) GetTxid() []byte {
	if m != nil {
		return m.Txid
	}
	return nil
}

func (m *Ticket) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func init() {
	proto.RegisterType((*AppTransactions)(nil), "protobuf.AppTransactions")
	proto.RegisterType((*AppTransaction)(nil), "protobuf.AppTransaction")
	proto.RegisterType((*FromCoin)(nil), "protobuf.FromCoin")
	proto.RegisterType((*TransactionFrom)(nil), "protobuf.TransactionFrom")
	proto.RegisterType((*ToCoin)(nil), "protobuf.ToCoin")
	proto.RegisterType((*TransactionTo)(nil), "protobuf.TransactionTo")
	proto.RegisterType((*Ticket)(nil), "protobuf.Ticket")
}

func init() { proto.RegisterFile("protobuf/transaction.proto", fileDescriptor_55be6871dfc7d2db) }

var fileDescriptor_55be6871dfc7d2db = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0x4a, 0xf3, 0x40,
	0x14, 0xc5, 0xc9, 0xa4, 0xcd, 0x57, 0x6e, 0xff, 0x7d, 0x5c, 0x04, 0x47, 0x57, 0x61, 0x16, 0x3a,
	0x08, 0x46, 0xe8, 0xc6, 0x85, 0xb8, 0x10, 0xc5, 0x07, 0x18, 0xfa, 0x02, 0xb1, 0x49, 0x65, 0xd0,
	0xce, 0x0d, 0xc9, 0xb4, 0xc4, 0x97, 0xf3, 0xd9, 0x64, 0x26, 0x8d, 0x49, 0xa4, 0xbb, 0x73, 0xcf,
	0x9c, 0xcc, 0xef, 0xe4, 0x0e, 0x5c, 0x16, 0x25, 0x59, 0x7a, 0xdb, 0x6f, 0xef, 0x6c, 0x99, 0x9a,
	0x2a, 0xdd, 0x58, 0x4d, 0x26, 0xf1, 0x26, 0x4e, 0xda, 0x33, 0xf1, 0x08, 0xcb, 0xa7, 0xa2, 0x58,
	0x77, 0x89, 0x0a, 0x6f, 0x20, 0xb4, 0x75, 0xc5, 0x83, 0x38, 0x94, 0xd3, 0x15, 0x4f, 0xda, 0x68,
	0x32, 0xcc, 0x29, 0x17, 0x12, 0xdf, 0x01, 0x2c, 0x86, 0x3e, 0x72, 0xf8, 0x77, 0xc8, 0xcb, 0x4a,
	0x93, 0xe1, 0x41, 0xcc, 0xe4, 0x5c, 0xb5, 0x23, 0x22, 0x8c, 0xec, 0x57, 0x91, 0x73, 0xe6, 0x6d,
	0xaf, 0xf1, 0x16, 0x46, 0xdb, 0x92, 0x76, 0x3c, 0x8c, 0x99, 0x9c, 0xae, 0x2e, 0x3a, 0x5a, 0xef,
	0xca, 0xd7, 0x92, 0x76, 0xca, 0xc7, 0xf0, 0x1a, 0x98, 0x25, 0x3e, 0xf2, 0xe1, 0xf3, 0x93, 0xe1,
	0x35, 0x29, 0x66, 0xc9, 0xb1, 0x2a, 0xfd, 0x6e, 0xf8, 0x38, 0x0e, 0xe5, 0x4c, 0x79, 0xed, 0xbc,
	0x2c, 0xb5, 0x29, 0x8f, 0xe2, 0xc0, 0x79, 0x4e, 0x8b, 0x17, 0x98, 0xb8, 0xeb, 0x9f, 0x49, 0x1b,
	0x5c, 0x00, 0xd3, 0x99, 0x2f, 0x3d, 0x53, 0x4c, 0x67, 0x28, 0x21, 0xb2, 0x7a, 0xf3, 0x91, 0x5b,
	0xce, 0xfc, 0x2e, 0xfe, 0xf7, 0x80, 0xde, 0x57, 0xc7, 0x73, 0xf1, 0x00, 0xcb, 0x3f, 0x7d, 0x51,
	0xc2, 0x78, 0x43, 0xda, 0xb4, 0x7b, 0xc4, 0xee, 0xdb, 0x96, 0xa7, 0x9a, 0x80, 0x48, 0x20, 0x5a,
	0xd3, 0xc9, 0x02, 0x67, 0x30, 0x3e, 0xa4, 0x9f, 0xfb, 0x66, 0x63, 0x33, 0xd5, 0x0c, 0xe2, 0x1e,
	0xe6, 0x83, 0xff, 0xc5, 0xab, 0x21, 0xaa, 0x5f, 0x93, 0xfa, 0xa0, 0x15, 0x44, 0x4d, 0x6f, 0xff,
	0x12, 0xf5, 0x2f, 0xca, 0x6b, 0x07, 0xd3, 0x26, 0xcb, 0xeb, 0xe3, 0xf3, 0x34, 0xc3, 0x4f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xf5, 0xf4, 0xa6, 0x86, 0x46, 0x02, 0x00, 0x00,
}
