// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/transaction.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Transactions struct {
	Txs                  []*Transaction `protobuf:"bytes,1,rep,name=txs" json:"txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Transactions) Reset()         { *m = Transactions{} }
func (m *Transactions) String() string { return proto.CompactTextString(m) }
func (*Transactions) ProtoMessage()    {}
func (*Transactions) Descriptor() ([]byte, []int) {
	return fileDescriptor_55be6871dfc7d2db, []int{0}
}

func (m *Transactions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transactions.Unmarshal(m, b)
}
func (m *Transactions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transactions.Marshal(b, m, deterministic)
}
func (m *Transactions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transactions.Merge(m, src)
}
func (m *Transactions) XXX_Size() int {
	return xxx_messageInfo_Transactions.Size(m)
}
func (m *Transactions) XXX_DiscardUnknown() {
	xxx_messageInfo_Transactions.DiscardUnknown(m)
}

var xxx_messageInfo_Transactions proto.InternalMessageInfo

func (m *Transactions) GetTxs() []*Transaction {
	if m != nil {
		return m.Txs
	}
	return nil
}

type Transaction struct {
	Version              *uint32          `protobuf:"varint,1,req,name=version" json:"version,omitempty"`
	Type                 *uint32          `protobuf:"varint,2,req,name=type" json:"type,omitempty"`
	From                 *TransactionFrom `protobuf:"bytes,3,req,name=from" json:"from,omitempty"`
	To                   *TransactionTo   `protobuf:"bytes,4,req,name=to" json:"to,omitempty"`
	Sign                 [][]byte         `protobuf:"bytes,5,rep,name=sign" json:"sign,omitempty"`
	Data                 []byte           `protobuf:"bytes,6,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_55be6871dfc7d2db, []int{1}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *Transaction) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Transaction) GetFrom() *TransactionFrom {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Transaction) GetTo() *TransactionTo {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Transaction) GetSign() [][]byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

func (m *Transaction) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type FromCoin struct {
	Id                   []byte    `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Ticket               []*Ticket `protobuf:"bytes,2,rep,name=ticket" json:"ticket,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FromCoin) Reset()         { *m = FromCoin{} }
func (m *FromCoin) String() string { return proto.CompactTextString(m) }
func (*FromCoin) ProtoMessage()    {}
func (*FromCoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_55be6871dfc7d2db, []int{2}
}

func (m *FromCoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FromCoin.Unmarshal(m, b)
}
func (m *FromCoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FromCoin.Marshal(b, m, deterministic)
}
func (m *FromCoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FromCoin.Merge(m, src)
}
func (m *FromCoin) XXX_Size() int {
	return xxx_messageInfo_FromCoin.Size(m)
}
func (m *FromCoin) XXX_DiscardUnknown() {
	xxx_messageInfo_FromCoin.DiscardUnknown(m)
}

var xxx_messageInfo_FromCoin proto.InternalMessageInfo

func (m *FromCoin) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *FromCoin) GetTicket() []*Ticket {
	if m != nil {
		return m.Ticket
	}
	return nil
}

type TransactionFrom struct {
	Coins                []*FromCoin `protobuf:"bytes,1,rep,name=coins" json:"coins,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TransactionFrom) Reset()         { *m = TransactionFrom{} }
func (m *TransactionFrom) String() string { return proto.CompactTextString(m) }
func (*TransactionFrom) ProtoMessage()    {}
func (*TransactionFrom) Descriptor() ([]byte, []int) {
	return fileDescriptor_55be6871dfc7d2db, []int{3}
}

func (m *TransactionFrom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionFrom.Unmarshal(m, b)
}
func (m *TransactionFrom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionFrom.Marshal(b, m, deterministic)
}
func (m *TransactionFrom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionFrom.Merge(m, src)
}
func (m *TransactionFrom) XXX_Size() int {
	return xxx_messageInfo_TransactionFrom.Size(m)
}
func (m *TransactionFrom) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionFrom.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionFrom proto.InternalMessageInfo

func (m *TransactionFrom) GetCoins() []*FromCoin {
	if m != nil {
		return m.Coins
	}
	return nil
}

type ToCoin struct {
	Id                   []byte   `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Value                []byte   `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToCoin) Reset()         { *m = ToCoin{} }
func (m *ToCoin) String() string { return proto.CompactTextString(m) }
func (*ToCoin) ProtoMessage()    {}
func (*ToCoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_55be6871dfc7d2db, []int{4}
}

func (m *ToCoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToCoin.Unmarshal(m, b)
}
func (m *ToCoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToCoin.Marshal(b, m, deterministic)
}
func (m *ToCoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToCoin.Merge(m, src)
}
func (m *ToCoin) XXX_Size() int {
	return xxx_messageInfo_ToCoin.Size(m)
}
func (m *ToCoin) XXX_DiscardUnknown() {
	xxx_messageInfo_ToCoin.DiscardUnknown(m)
}

var xxx_messageInfo_ToCoin proto.InternalMessageInfo

func (m *ToCoin) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ToCoin) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type TransactionTo struct {
	Coins                []*ToCoin `protobuf:"bytes,1,rep,name=coins" json:"coins,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TransactionTo) Reset()         { *m = TransactionTo{} }
func (m *TransactionTo) String() string { return proto.CompactTextString(m) }
func (*TransactionTo) ProtoMessage()    {}
func (*TransactionTo) Descriptor() ([]byte, []int) {
	return fileDescriptor_55be6871dfc7d2db, []int{5}
}

func (m *TransactionTo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionTo.Unmarshal(m, b)
}
func (m *TransactionTo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionTo.Marshal(b, m, deterministic)
}
func (m *TransactionTo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionTo.Merge(m, src)
}
func (m *TransactionTo) XXX_Size() int {
	return xxx_messageInfo_TransactionTo.Size(m)
}
func (m *TransactionTo) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionTo.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionTo proto.InternalMessageInfo

func (m *TransactionTo) GetCoins() []*ToCoin {
	if m != nil {
		return m.Coins
	}
	return nil
}

type Ticket struct {
	Txid                 []byte   `protobuf:"bytes,1,req,name=txid" json:"txid,omitempty"`
	Index                *uint32  `protobuf:"varint,2,req,name=index" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ticket) Reset()         { *m = Ticket{} }
func (m *Ticket) String() string { return proto.CompactTextString(m) }
func (*Ticket) ProtoMessage()    {}
func (*Ticket) Descriptor() ([]byte, []int) {
	return fileDescriptor_55be6871dfc7d2db, []int{6}
}

func (m *Ticket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ticket.Unmarshal(m, b)
}
func (m *Ticket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ticket.Marshal(b, m, deterministic)
}
func (m *Ticket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ticket.Merge(m, src)
}
func (m *Ticket) XXX_Size() int {
	return xxx_messageInfo_Ticket.Size(m)
}
func (m *Ticket) XXX_DiscardUnknown() {
	xxx_messageInfo_Ticket.DiscardUnknown(m)
}

var xxx_messageInfo_Ticket proto.InternalMessageInfo

func (m *Ticket) GetTxid() []byte {
	if m != nil {
		return m.Txid
	}
	return nil
}

func (m *Ticket) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func init() {
	proto.RegisterType((*Transactions)(nil), "protobuf.Transactions")
	proto.RegisterType((*Transaction)(nil), "protobuf.Transaction")
	proto.RegisterType((*FromCoin)(nil), "protobuf.FromCoin")
	proto.RegisterType((*TransactionFrom)(nil), "protobuf.TransactionFrom")
	proto.RegisterType((*ToCoin)(nil), "protobuf.ToCoin")
	proto.RegisterType((*TransactionTo)(nil), "protobuf.TransactionTo")
	proto.RegisterType((*Ticket)(nil), "protobuf.Ticket")
}

func init() { proto.RegisterFile("protobuf/transaction.proto", fileDescriptor_55be6871dfc7d2db) }

var fileDescriptor_55be6871dfc7d2db = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x41, 0x4e, 0xf3, 0x30,
	0x10, 0x85, 0x15, 0xa7, 0xcd, 0x5f, 0x4d, 0xd3, 0x1f, 0x34, 0x02, 0x61, 0x58, 0x45, 0x5e, 0x50,
	0x6f, 0x08, 0x52, 0x37, 0x5d, 0xb0, 0x04, 0x71, 0x00, 0x2b, 0x17, 0x08, 0x49, 0x8a, 0x2c, 0xa8,
	0xa7, 0x4a, 0xdc, 0x2a, 0x9c, 0x8d, 0xcb, 0x21, 0x3b, 0x0d, 0x4d, 0x51, 0x76, 0x33, 0x6f, 0x5e,
	0xf2, 0x3d, 0xcf, 0xc0, 0xdd, 0xae, 0x26, 0x4b, 0x6f, 0xfb, 0xcd, 0xa3, 0xad, 0x73, 0xd3, 0xe4,
	0x85, 0xd5, 0x64, 0x52, 0x2f, 0xe2, 0xac, 0x9f, 0x89, 0x35, 0xc4, 0xd9, 0x69, 0xdc, 0xe0, 0x12,
	0x42, 0xdb, 0x36, 0x3c, 0x48, 0x42, 0x39, 0x5f, 0x5d, 0xa7, 0xbd, 0x2f, 0x1d, 0x98, 0x94, 0x73,
	0x88, 0xef, 0x00, 0xe6, 0x03, 0x11, 0x39, 0xfc, 0x3b, 0x54, 0x75, 0xa3, 0xc9, 0xf0, 0x20, 0x61,
	0x72, 0xa1, 0xfa, 0x16, 0x11, 0x26, 0xf6, 0x6b, 0x57, 0x71, 0xe6, 0x65, 0x5f, 0xe3, 0x03, 0x4c,
	0x36, 0x35, 0x6d, 0x79, 0x98, 0x30, 0x39, 0x5f, 0xdd, 0x8e, 0x72, 0x5e, 0x6b, 0xda, 0x2a, 0x6f,
	0xc3, 0x25, 0x30, 0x4b, 0x7c, 0xe2, 0xcd, 0x37, 0xa3, 0xe6, 0x8c, 0x14, 0xb3, 0xe4, 0x58, 0x8d,
	0x7e, 0x37, 0x7c, 0x9a, 0x84, 0x32, 0x56, 0xbe, 0x76, 0x5a, 0x99, 0xdb, 0x9c, 0x47, 0x49, 0xe0,
	0x34, 0x57, 0x8b, 0x17, 0x98, 0xb9, 0xdf, 0x3f, 0x93, 0x36, 0xf8, 0x1f, 0x98, 0x2e, 0x7d, 0xe8,
	0x58, 0x31, 0x5d, 0xa2, 0x84, 0xc8, 0xea, 0xe2, 0xa3, 0xb2, 0x9c, 0xf9, 0x2d, 0x5c, 0x0e, 0x80,
	0x5e, 0x57, 0xc7, 0xb9, 0x78, 0x82, 0x8b, 0x3f, 0x79, 0x51, 0xc2, 0xb4, 0x20, 0x6d, 0xfa, 0x0d,
	0xe2, 0xe9, 0xdb, 0x9e, 0xa7, 0x3a, 0x83, 0x48, 0x21, 0xca, 0x68, 0x34, 0xc0, 0x15, 0x4c, 0x0f,
	0xf9, 0xe7, 0xbe, 0xdb, 0x58, 0xac, 0xba, 0x46, 0xac, 0x61, 0x71, 0xf6, 0x5e, 0xbc, 0x3f, 0x47,
	0x0d, 0x63, 0xd2, 0x10, 0xb4, 0x82, 0xa8, 0xcb, 0xed, 0x2f, 0xd1, 0xfe, 0xa2, 0x7c, 0xed, 0x60,
	0xda, 0x94, 0x55, 0x7b, 0x3c, 0x4f, 0xd7, 0xfc, 0x04, 0x00, 0x00, 0xff, 0xff, 0x92, 0x49, 0x3f,
	0xf2, 0x3d, 0x02, 0x00, 0x00,
}
